<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Artemis_Banking_Pro.Core.Application</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\DtoToViewModelsAndReverse\" />
    <Folder Include="Mappings\EntitieToDtosAndReverse\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ArtemisBankingPro.Core.Domain\ArtemisBankingPro.Core.Domain.csproj" />
  </ItemGroup>

</Project>
